services:
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/chroma/chroma
    networks:
      - rag-network

  langflow:
    image: langflowai/langflow:latest
    ports:
      - "7860:7860"
    depends_on:
      - chromadb
    restart: on-failure
    volumes:
      - ./langflow_data:/app/langflow
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge
